### ISSUE TITLE
Compodoc Hosting

### ISSUE THREAD

**Issue by mimischi** [GeoMatDigital/app-geomat#10]
Wie ist denn euer Plan, wie die Compodoc Dokumentation gehostet wird? Man könnte Travis-CI so einrichten, dass es das Ding baut und dann auf eine eigene Repository (z.B. `GeoMatDigital/app-documentation`) pusht (siehe [StackOverflow](https://stackoverflow.com/a/43967991/4791226)). Dann kann man mit Hilfe von [GitHub Pages](https://pages.github.com/) kostenloses und simples Hosting haben. Direkt aus der Respository!

Soll ich versuchen das einzurichten?

Edit: An [diesem Beispiel](https://github.com/steveklabnik/automatically_update_github_pages_with_travis_example) richten viele den Deploy ein.

**Comment by mimischi** [comment]
An [diesem Beispiel](https://github.com/steveklabnik/automatically_update_github_pages_with_travis_example) richten viele den Deploy ein.

**Comment by BastianKrones** [comment]
Ja, ne coole Idee. Werde ich die Tage mal umsetzen :)

**Comment by BastianKrones** [comment]
Since we are using sentry.io. Travis-CI is an overkill for jsut uploading documentation generated by compodoc. Currently it's output is uploaded to [physikelearning.de/geomat](https://physikonline.uni-frankfurt.de/geomat/)
