### ISSUE TITLE
Adding padding to homepage

### ISSUE THREAD

**Issue by BastianKrones** [GeoMatDigital/app-geomat#37]
### Description
In desktop-view there is much free space, to fit content better, padding should be added to the list items.

**Comment by BastianKrones** [comment]
Since only css-changes have been made, you have to clear the browser's cache to force a new page-load and see the new content.

**Comment by sheepyhollow** [comment]
You managed to surprise me as I did do a cache purge a few minutes ago :grin:

**Comment by sheepyhollow** [comment]
Nur Rückfrage: das Padding ist nur im "Desktop-View" zu sehen und nicht auf mobiler Größe?
Issue kann dann wieder geschlossen werden.

**Comment by sheepyhollow** [comment]
Ist, wie es sein soll.
