### ISSUE TITLE
Add info for non-existing minerals 

### ISSUE THREAD

**Issue by BastianKrones** [GeoMatDigital/app-geomat#39]
### Description
Currently non existing minerals are not clickable in the prifiles-list. It should be changed to:
Click on the item and navigate to the new view which shows a message that there are no minerals for this category.

**Comment by sheepyhollow** [comment]
https://de.wikipedia.org/wiki/Unobtainium ... :wink:

**Comment by BastianKrones** [comment]
Add new page info if no minerals are available for selected catergory.
Therefore 2 new images for 'Borate' and 'Organische Verbindungen' are currently missing.
