### ISSUE TITLE
Adjust "Varietätsname"

### ISSUE THREAD

**Issue by BastianKrones** [GeoMatDigital/app-geomat#46]
### Description

Currently "trivialname" is shown in header of every profile-list-view and profile-detail-view.
If "varietäts-name" is available display "Varietät" instead of trivial-name

**Comment by BastianKrones** [comment]
Displaying 'display_name' on profile-details-view

**Comment by sheepyhollow** [comment]
Wenn ein **Varietätsname** vorliegt, dann wird dieser im Steckbrieftitel (und in der Übersicht) angezeigt.
Wenn nicht, wird der **Mineralname** angezeigt.

Der **Trivialname** taucht _nur_ als Feld im Steckbrief und _nie_ im Titel/in der Übersicht auf.
Wenn Trivialname = Mineralname, erscheint das Feld Trivialname *nicht*.

**Comment by HaUFR** [comment]
Hardcode entfernen und mit der API arbeiten
