### ISSUE TITLE
Anzeige Bilder im Steckbrief (profiles)

### ISSUE THREAD

**Issue by sheepyhollow** [GeoMatDigital/app-geomat#56]
Im Steckbrief soll je Mineral ein (ausgewähltes) Bild angezeigt werden.
Die Bildadressen werden mitgeliefert und müssten nur noch (in passender Größe) eingebaut werden.

**Comment by HaUFR** [comment]
Steckbriefbilder, welche von der API (geomat.uni-frankfurt.de/api/profiles) mitgegeben werden, sollen in Profiles-Details angezeigt werden
