### ISSUE TITLE
Fragentitel (quiz)

### ISSUE THREAD

**Issue by sheepyhollow** [GeoMatDigital/app-geomat#65]
Aktuell wird "Question 1" etc. angezeigt.

Braucht man diese Anzeige überhaupt? Was soll als Titel sonst angezeigt werden?
- Frage x von <Gesamtzahl>
- soll ich die ID sehen oder eine laufende Nummerierung (bei Zufallsfragen)?
- Soll das Keyword mit angezeigt werden?

**Comment by HaUFR** [comment]
Fragentitel mit dem Tag ersetzen
