### ISSUE TITLE
Zurück-Button im Info-Bereich

### ISSUE THREAD

**Issue by sheepyhollow** [GeoMatDigital/app-geomat#70]
Wenn man über das Hamburgermenü auf die Info-Seite geht, fehlt der "Zurück"-Pfeil.
Damit wird man in der mobilen Ansicht auf der Infoseite gefangen, da man nicht mehr zurück kommt.
Wenn man die Infoseite über die Schaltfläche der Startseite aufruft, ist der Zurück-Pfeil da.

**Comment by HaUFR** [comment]
Code im Front-End soll beim Aufruf der Info-Seite wieder auf die Home Seite zurückweisen
